let auth0=null;const api=_auth0_conf.api+"?apikey="+_auth0_conf.apiKey;const differentAudienceOptions={issuer:_auth0_conf.issuer,audience:_auth0_conf.audience}
window.addEventListener("load",()=>loadEdit(),false);async function loadEdit(){await configureClient();const query=window.location.search;if(query.includes("code=")&&query.includes("state=")){if(!query.includes("code=null")||!query.includes("state=null")){await auth0.handleRedirectCallback();}
var currURL=window.location.href;var retorno=currURL.split("?")[0];window.history.replaceState({},document.title,retorno);}
updateUI();}
const configureClient=async()=>{auth0=await createAuth0Client({domain:_auth0_conf.domain_cla,client_id:_auth0_conf.client_id,cacheLocation:'localstorage',useRefreshTokens:true});};const updateUI=async()=>{var user=window.localStorage.getItem("wads_userProfile");if(user==null){const isAuthenticated=await auth0.isAuthenticated();if(isAuthenticated){user=await auth0.getUser();const token=await auth0.getTokenSilently(differentAudienceOptions);getUserApi(token,user);}}else{setTimeout(function(){$(document).trigger("wa.ready");},0);user=JSON.parse(user);user=user.value;var status=false;if(user.subscriptionProducts!=''){status=true;}
verificaSuscripcion(status);}
$(document).trigger("wa.auth0.ready");showUser(user);};function showUser(user){if(user){var name=user.hasOwnProperty("https://clarin.com/etiquetaUsuario")?user["https://clarin.com/etiquetaUsuario"]:user.name;$(".paseLog.pase_login.not_logged").hide();$(".paseLog.pase_login.logged").show();$("#pase-panel-login").hide();$(".email-usuario").html(user.email);$("#userFirstName").html("Hola, "+name);if(typeof user.picture!="undefined"&&user.picture!=""){htmlAvatar='<img src="'+user.picture+'" class="avatar" alt="'+name+'" />';}else{htmlAvatar='<div class="avatar default"></div>';}
$(".icon-profile.pase_login.avatar").html(htmlAvatar);if(typeof user.jwt!='undefined'){$("#wb_meter").attr('jwt',user.jwt);}}else{setTimeout(function(){$(document).trigger("wa.ready");},0);$(".paseLog.pase_login.logged").hide();$(".icon-profile.pase_login.avatar").html("");$(".email-usuario").html("");$("#userFirstName").html("");$(".subscription").show();$("#pase-panel-login").show();$("#loginLogout").show();$(".suscribe").show();$(".comments").addClass("comment-not");$(".paseLog.pase_login.not_logged").show();$(".nolog").show();$(".noSub").hide();$(".suscrito").hide();if(_auth0_conf.apiKey=="ole"){$('#loginLogout').html('<p>Ingresar </p><span class="ic-user"></span>');$('.title_suscripcion').show();$('.title_suscripcion').html('Suscribirme');$("#suscripcion").show();$('.suscribeteBtn').html('Suscribirme');$('.suscribirmeBtn').show();$('.suscribiteBtn').hide();}
$("#wb_meter").attr('jwt','anonymous');}}
function getUserApi(token,user){$(document).trigger("wa.login",user);$.ajax({type:"GET",beforeSend:function(request){request.setRequestHeader("Content-Type","application/json");request.setRequestHeader("Authorization","Bearer "+token);},url:api,success:function(response){var status='';if(response.user==null){status=false;}else if(response.user.data.subscriptions.length){status=true;}
verificaSuscripcion(status);storageUser(user,response,token);}});};function verificaSuscripcion(status){if(!status){$(".suscribe").show();$(".subscription").show();$('.title_suscripcion').html('Suscribite');$('.title_suscripcion').show();$("#suscripcion").show();$("li#misuscripcion").hide();$(".hola").removeClass("sus-name");$(".comments").removeClass("comment-ok");$(".comments").addClass("comment-not");$(".nolog").hide();$(".noSub").show();$(".suscrito").hide();$(".gig-comments-composebox").css({'display':'none','background':'yellow'})
$('.suscribeteBtn').html('Suscribite');$('.suscribirmeBtn').hide();$('.suscribiteBtn').show();}else{$("li#misuscripcion").show();$(".subscription").hide();$("#suscripcion").hide();$(".suscribe").hide();$(".hola").addClass("sus-name");$(".suscrito").show();$(".comments").addClass("comment-ok")
$(".nolog").hide();$(".noSub").hide();$(".suscrito").show();}}
const storageUser=(user,response,token)=>{setTimeout(function(){$(document).trigger("wa.ready");},0);pase=''
if(response.hasOwnProperty("https://clarin.com/idPase")){pase=user["https://clarin.com/idPase"]}
else{pase=user.sub}
setIdPase(pase);setToken(token);let userStorage={uid:pase,nombre:user.name,name:response.hasOwnProperty("https://clarin.com/etiquetaUsuario")?response["https://clarin.com/etiquetaUsuario"]:user.name,apellido:"",email:user.email,genero:response.hasOwnProperty("https://clarin.com/genero")?response["https://clarin.com/genero"]:'',fotoURL:user.picture,picture:user.picture,thumbnailURL:"",fechaNacimiento:response.hasOwnProperty("https://clarin.com/fechaNacimiento")?response["https://clarin.com/fechaNacimiento"]:'',apodo:user.nickname,estado:"ACTIVO",proveedorDeIdentidad:user.sub.split("|")[0],proveedorDeLogin:user.sub.split("|")[0],atributoMap:{},valorAtributoList:[],direccion:{},siteUID:true,UIDSignature:"",subscriptionStatus:response.user!=null?"subscribed":'',subscriptionProducts:response.user!=null?response.user.data.subscriptions.map((sus)=>{return sus.pId}):'',id:user.sub,sessionId:response.user!=null?response.user._id:'',sessionStatus:response.user!=null?"valid":'',jwt:response.jwt!=null?response.jwt:'',auth0:user}
setOleCookies(userStorage.genero,userStorage.fechaNacimiento);$("#wb_meter").attr('jwt',userStorage.jwt);var status=false;if(userStorage.subscriptionProducts!=''){status=true;}
verificaSuscripcion(status);WAuth.set(userStorage);$(document).trigger("wa.user.update",userStorage);getUser(()=>{},false)};const setIdPase=(pase)=>{$.cookie("idPase",pase,{path:_wa_conf.cookieSID.path,domain:_wa_conf.cookieSID.domain,expires:getExpireDate()});}
const setOleCookies=(genero,fechaNac)=>{$.cookie("Pase-genero",genero,{path:_wa_conf.cookieSID.path,domain:_wa_conf.cookieSID.domain,expires:getExpireDate()});$.cookie("Pase-fecNac",fechaNac,{path:_wa_conf.cookieSID.path,domain:_wa_conf.cookieSID.domain,expires:getExpireDate()});}
const setToken=(token)=>{$.cookie(_wa_conf.cookiesPrefix+"__token_auth0",token,{path:_wa_conf.cookieSID.path,domain:_wa_conf.cookieSID.domain});}
$(document).on('click','.bt_ingresar',function(event){const options={redirect_uri:window.location.origin};$.cookie("auth0_redir",window.location.href,{path:_wa_conf.cookieSID.path,domain:_wa_conf.cookieSID.domain,expires:getExpireDate()});auth0.loginWithRedirect(options);});$(document).on('click','.pase_logoff',function(event){removeUser();$(document).trigger("wa.logout");$.cookie("auth0_redir",window.location.href,{path:_wa_conf.cookieSID.path,domain:_wa_conf.cookieSID.domain,expires:getExpireDate()});auth0.logout({returnTo:window.location.origin});});newWeizenbock={};newWeizenbock.Dataset=function(options){if(!options||!options.name){throw new TypeError("Bad arguments");}
let prefix="wads_";this.name=prefix+options.name;this.ttl=(options.ttl)?options.ttl:null;return this;}
newWeizenbock.Dataset.instances={};newWeizenbock.Dataset.prototype.getUserSync=function(){return WAuth.getAll({forceNotExpire:true});}
newWeizenbock.Dataset.getInstance=(name,options)=>{if(newWeizenbock.Dataset.instances[name]){return newWeizenbock.Dataset.instances[name];}
options=options||{};options.name=name;var ds=new newWeizenbock.Dataset(options);newWeizenbock.Dataset.instances[name]=ds;return ds;}
newWeizenbock.Dataset.prototype.set=(...arg)=>{var self=WAuth;if(arg.length<1||arg.length>2){throw new TypeError("Bad arguments");}
if(arg.length==2){var data=WAuth.getAll({forceNotExpire:true})||{};data[arg[0]]=arg[1];}else{var data=arg[0];}
var value={value:data,created_at:new Date().getTime()};window.localStorage.setItem(self.name,JSON.stringify(value));}
newWeizenbock.Dataset.prototype.get=(key)=>{var data=WAuth.getAll({forceNotExpire:true});if(!data||!data[key]){return null;}
return data[key];}
newWeizenbock.Dataset.prototype.getAll=(settings)=>{var self=WAuth;var data=window.localStorage.getItem(self.name);if(!data){return null;}
try{data=JSON.parse(data);}catch(e){return null;}
return data.value;}
newWeizenbock.Dataset.prototype.delete=()=>{window.localStorage.removeItem(WAuth.name);}
const WAuth=newWeizenbock.Dataset.getInstance("userProfile",{ttl:5*60*1000});const getUser=(cb,forceEvents)=>{var user=WAuth.getAll({forceNotExpire:true});if(user){var sid=$.cookie(_wa_conf.cookiesPrefix+_wa_conf.cookieSID.name);if(!sid){$.cookie(_wa_conf.cookiesPrefix+_wa_conf.cookieSID.name,user.sessionId,{path:_wa_conf.cookieSID.path,domain:_wa_conf.cookieSID.domain,expires:getExpireDate()});}
return cb(null,user);}}
const removeUser=()=>{$("#wb_meter").removeAttr('jwt');$.removeCookie(_wa_conf.cookiesPrefix+_wa_conf.cookieSID.name,{path:_wa_conf.cookieSID.path,domain:_wa_conf.cookieSID.domain,expires:getExpireDate()});$.removeCookie(_wa_conf.cookiesPrefix+"__token_auth0",{path:_wa_conf.cookieSID.path,domain:_wa_conf.cookieSID.domain});$.removeCookie("idPase",{path:_wa_conf.cookieSID.path,domain:_wa_conf.cookieSID.domain,expires:getExpireDate()});$.removeCookie("Pase-genero",{path:_wa_conf.cookieSID.path,domain:_wa_conf.cookieSID.domain,expires:getExpireDate()});$.removeCookie("Pase-fecNac",{path:_wa_conf.cookieSID.path,domain:_wa_conf.cookieSID.domain,expires:getExpireDate()});if(window.vf!=undefined){window.vf.session.logout();window.vf.context.reset();}
WAuth.delete();}
function getExpireDate(){var now=new Date()
return new Date(now.getFullYear()+1,now.getMonth(),now.getDate())}
$(document).on("wa.modal.open",function(){$('html').css("overflow-y","hidden");});$(document).on("wa.modal.close",function(){$('html').css("overflow-y","scroll");});var toggle=false;$(document).on('click','.pase_LoggedIn',function(event){if(_auth0_conf.apiKey=="ole"){if(!toggle){$(".opciones.subnav").slideDown(300);toggle=true;}else{$(".opciones.subnav").slideUp(300);toggle=false;}}});